#!/bin/sh
# Kodama Spirit Hook — notifies your coding companion of agent activity
# This file is auto-generated by Kodama. Safe to delete if you uninstall.
KODAMA_STATE="/Users/peerlesswu/IdeaProjects/osdev/algorithm_help/.kodama/agent-state.json"
write_state() {
  echo "{\"status\":\"$1\",\"timestamp\":$(date +%s)000}" > "$KODAMA_STATE" 2>/dev/null
}

case "$CLAUDE_HOOK_EVENT" in
  pre_tool_use)  write_state "thinking" ;;
  post_tool_use) write_state "writing" ;;
  pre_submit)    write_state "waiting" ;;
  post_submit)   write_state "complete" ;;
  *)             write_state "active" ;;
esac
