-- ============================================
-- 算法深度理解引擎 - 种子数据初始化
-- ============================================

-- 1. 插入算法模式
INSERT INTO algorithm_patterns (id, name, category, signals, template, variants, related_problems, created_at, updated_at) VALUES
('dp', '动态规划', '经典模式', '["最优子结构","重叠子问题","状态转移方程","求最值/计数"]', '{"python":"def solve(n):\\n    dp = [0] * (n+1)\\n    dp[0] = base_case\\n    for i in range(1, n+1):\\n        dp[i] = transition(dp[i-1])\\n    return dp[n]","java":"public int solve(int n) {\\n    int[] dp = new int[n+1];\\n    dp[0] = basCase;\\n    for (int i = 1; i <= n; i++) {\\n        dp[i] = transition(dp[i-1]);\\n    }\\n    return dp[n];\\n}"}', '["记忆化搜索","空间优化（滚动数组）","区间DP","树形DP","状压DP"]', '["p-climbing-stairs","p-house-robber","p-longest-common-subsequence","p-coin-change","p-edit-distance"]', 1719000000000, 1719000000000),
('two-pointers', '双指针', '经典模式', '["有序数组","对撞条件","滑动窗口变体","O(n)要求"]', '{"python":"def two_pointers(arr):\\n    left, right = 0, len(arr)-1\\n    while left < right:\\n        if condition(arr[left], arr[right]):\\n            # found\\n            break\\n        elif need_move_left:\\n            left += 1\\n        else:\\n            right -= 1","java":"public void twoPointers(int[] arr) {\\n    int left = 0, right = arr.length - 1;\\n    while (left < right) {\\n        // logic\\n    }\\n}"}', '["快慢指针","滑动窗口","三指针分区"]', '["p-two-sum-sorted","p-three-sum","p-container-with-most-water","p-remove-duplicates"]', 1719000000000, 1719000000000),
('sliding-window', '滑动窗口', '经典模式', '["连续子数组/子串","固定/可变长度窗口","最长/最短满足条件"]', '{"python":"def sliding_window(s):\\n    left = 0\\n    window = {}\\n    result = 0\\n    for right in range(len(s)):\\n        # expand window\\n        window[s[right]] = window.get(s[right], 0) + 1\\n        while need_shrink(window):\\n            window[s[left]] -= 1\\n            left += 1\\n        result = max(result, right - left + 1)\\n    return result"}', '["固定窗口","可变窗口","双端队列优化"]', '["p-longest-substring-without-repeating","p-minimum-window-substring","p-max-sliding-window"]', 1719000000000, 1719000000000),
('backtracking', '回溯', '经典模式', '["所有可能","排列组合","约束满足","剪枝优化"]', '{"python":"def backtrack(path, choices):\\n    if is_goal(path):\\n        result.append(path[:])\\n        return\\n    for choice in choices:\\n        if is_valid(choice):\\n            path.append(choice)\\n            backtrack(path, next_choices)\\n            path.pop()"}', '["排列","组合","子集","N皇后","数独"]', '["p-permutations","p-combinations","p-subsets","p-n-queens"]', 1719000000000, 1719000000000),
('bfs', '广度优先搜索', '图与树', '["最短路径","层序遍历","多源BFS","状态空间搜索"]', '{"python":"from collections import deque\\ndef bfs(start):\\n    queue = deque([start])\\n    visited = {start}\\n    while queue:\\n        node = queue.popleft()\\n        for neighbor in get_neighbors(node):\\n            if neighbor not in visited:\\n                visited.add(neighbor)\\n                queue.append(neighbor)"}', '["多源BFS","双向BFS","拓扑排序"]', '["p-binary-tree-level-order","p-word-ladder","p-rotting-oranges"]', 1719000000000, 1719000000000);

-- 2. 插入题目数据（20 道经典题）
INSERT INTO problems (id, title, difficulty, tags, description, constraints, examples, company_tags, created_at, updated_at) VALUES
('p-two-sum', '两数之和', 'EASY', '["数组","哈希表"]', '给定一个整数数组 nums 和一个整数目标值 target，请你在该数组中找出和为目标值 target 的那两个整数，并返回它们的数组下标。', '["2 <= nums.length <= 10^4","-10^9 <= nums[i] <= 10^9","-10^9 <= target <= 10^9","只会存在一个有效答案"]', '["输入：nums = [2,7,11,15], target = 9\\n输出：[0,1]","输入：nums = [3,2,4], target = 6\\n输出：[1,2]"]', '["Google","Amazon","Apple","Microsoft","Meta"]', 1719000000000, 1719000000000),
('p-add-two-numbers', '两数相加', 'MEDIUM', '["链表","数学","递归"]', '给你两个非空的链表，表示两个非负的整数。它们每位数字都是按照逆序的方式存储的，并且每个节点只能存储一位数字。请你将两个数相加，并以相同形式返回一个表示和的链表。', '["每个链表中的节点数在范围 [1, 100] 内","0 <= Node.val <= 9","题目数据保证列表表示的数字不含前导零"]', '["输入：l1 = [2,4,3], l2 = [5,6,4]\\n输出：[7,0,8]"]', '["Amazon","Microsoft","Google"]', 1719000000000, 1719000000000),
('p-longest-substring-without-repeating', '无重复字符的最长子串', 'MEDIUM', '["哈希表","字符串","滑动窗口"]', '给定一个字符串 s，请你找出其中不含有重复字符的最长子串的长度。', '["0 <= s.length <= 5 * 10^4","s 由英文字母、数字、符号和空格组成"]', '["输入: s = \\"abcabcbb\\"\\n输出: 3","输入: s = \\"bbbbb\\"\\n输出: 1"]', '["Amazon","Google","Microsoft","Meta"]', 1719000000000, 1719000000000),
('p-median-of-two-sorted-arrays', '寻找两个正序数组的中位数', 'HARD', '["数组","二分查找","分治"]', '给定两个大小分别为 m 和 n 的正序（从小到大）数组 nums1 和 nums2。请你找出并返回这两个正序数组的中位数。算法的时间复杂度应该为 O(log (m+n))。', '["nums1.length == m","nums2.length == n","0 <= m <= 1000","0 <= n <= 1000"]', '["输入：nums1 = [1,3], nums2 = [2]\\n输出：2.00000"]', '["Google","Amazon","Apple"]', 1719000000000, 1719000000000),
('p-longest-palindromic-substring', '最长回文子串', 'MEDIUM', '["字符串","动态规划"]', '给你一个字符串 s，找到 s 中最长的回文子串。', '["1 <= s.length <= 1000","s 仅由数字和英文字母组成"]', '["输入：s = \\"babad\\"\\n输出：\\"bab\\""]', '["Amazon","Microsoft","Meta"]', 1719000000000, 1719000000000),
('p-climbing-stairs', '爬楼梯', 'EASY', '["数学","动态规划","记忆化搜索"]', '假设你正在爬楼梯。需要 n 阶你才能到达楼顶。每次你可以爬 1 或 2 个台阶。你有多少种不同的方法可以爬到楼顶呢？', '["1 <= n <= 45"]', '["输入：n = 2\\n输出：2","输入：n = 3\\n输出：3"]', '["Google","Amazon","Apple"]', 1719000000000, 1719000000000),
('p-binary-tree-level-order', '二叉树的层序遍历', 'MEDIUM', '["树","BFS","二叉树"]', '给你二叉树的根节点 root，返回其节点值的层序遍历。（即逐层地，从左到右访问所有节点）。', '["树中节点数目在范围 [0, 2000] 内","-1000 <= Node.val <= 1000"]', '["输入：root = [3,9,20,null,null,15,7]\\n输出：[[3],[9,20],[15,7]]"]', '["Amazon","Microsoft","Meta"]', 1719000000000, 1719000000000),
('p-maximum-subarray', '最大子数组和', 'MEDIUM', '["数组","分治","动态规划"]', '给你一个整数数组 nums，请你找出一个具有最大和的连续子数组（子数组最少包含一个元素），返回其最大和。', '["1 <= nums.length <= 10^5","-10^4 <= nums[i] <= 10^4"]', '["输入：nums = [-2,1,-3,4,-1,2,1,-5,4]\\n输出：6"]', '["Amazon","Google","Microsoft","Apple"]', 1719000000000, 1719000000000),
('p-merge-intervals', '合并区间', 'MEDIUM', '["数组","排序"]', '以数组 intervals 表示若干个区间的集合，请你合并所有重叠的区间，并返回一个不重叠的区间数组。', '["1 <= intervals.length <= 10^4","intervals[i].length == 2"]', '["输入：intervals = [[1,3],[2,6],[8,10],[15,18]]\\n输出：[[1,6],[8,10],[15,18]]"]', '["Google","Meta","Microsoft"]', 1719000000000, 1719000000000),
('p-coin-change', '零钱兑换', 'MEDIUM', '["数组","动态规划","BFS"]', '给你一个整数数组 coins 表示不同面额的硬币和一个整数 amount 表示总金额。计算可以凑成总金额所需的最少硬币个数。', '["1 <= coins.length <= 12","1 <= coins[i] <= 2^31 - 1","0 <= amount <= 10^4"]', '["输入：coins = [1, 2, 5], amount = 11\\n输出：3"]', '["Amazon","Google","Apple"]', 1719000000000, 1719000000000);

INSERT INTO problems (id, title, difficulty, tags, description, constraints, examples, company_tags, created_at, updated_at) VALUES
('p-three-sum', '三数之和', 'MEDIUM', '["数组","双指针","排序"]', '给你一个整数数组 nums，判断是否存在三元组 [nums[i], nums[j], nums[k]] 满足 i != j、i != k 且 j != k，同时还满足 nums[i] + nums[j] + nums[k] == 0。', '["3 <= nums.length <= 3000","-10^5 <= nums[i] <= 10^5"]', '["输入：nums = [-1,0,1,2,-1,-4]\\n输出：[[-1,-1,2],[-1,0,1]]"]', '["Amazon","Meta","Google","Microsoft"]', 1719000000000, 1719000000000),
('p-container-with-most-water', '盛最多水的容器', 'MEDIUM', '["贪心","数组","双指针"]', '给定一个长度为 n 的整数数组 height。找出其中的两条线，使得它们与 x 轴共同构成的容器可以容纳最多的水。', '["n == height.length","2 <= n <= 10^5","0 <= height[i] <= 10^4"]', '["输入：[1,8,6,2,5,4,8,3,7]\\n输出：49"]', '["Amazon","Google","Meta"]', 1719000000000, 1719000000000),
('p-valid-parentheses', '有效的括号', 'EASY', '["栈","字符串"]', '给定一个只包括 (){}[] 的字符串 s，判断字符串是否有效。', '["1 <= s.length <= 10^4","s 仅由括号 (){}[] 组成"]', '["输入：s = \\"()\\"\\n输出：true","输入：s = \\"()[]{}\\"\\n输出：true"]', '["Amazon","Google","Meta","Microsoft"]', 1719000000000, 1719000000000),
('p-merge-two-sorted-lists', '合并两个有序链表', 'EASY', '["递归","链表"]', '将两个升序链表合并为一个新的升序链表并返回。新链表是通过拼接给定的两个链表的所有节点组成的。', '["两个链表的节点数目范围是 [0, 50]","-100 <= Node.val <= 100"]', '["输入：l1 = [1,2,4], l2 = [1,3,4]\\n输出：[1,1,2,3,4,4]"]', '["Amazon","Microsoft","Apple"]', 1719000000000, 1719000000000),
('p-house-robber', '打家劫舍', 'MEDIUM', '["数组","动态规划"]', '你是一个专业的小偷，计划偷窃沿街的房屋。每间房内都藏有一定的现金，影响你偷窃的唯一制约因素就是相邻的房屋装有相互连通的防盗系统。', '["1 <= nums.length <= 100","0 <= nums[i] <= 400"]', '["输入：[1,2,3,1]\\n输出：4","输入：[2,7,9,3,1]\\n输出：12"]', '["Amazon","Google","Microsoft"]', 1719000000000, 1719000000000),
('p-longest-common-subsequence', '最长公共子序列', 'MEDIUM', '["字符串","动态规划"]', '给定两个字符串 text1 和 text2，返回这两个字符串的最长公共子序列的长度。如果不存在公共子序列，返回 0。', '["1 <= text1.length, text2.length <= 1000","text1 和 text2 仅由小写英文字符组成"]', '["输入：text1 = \\"abcde\\", text2 = \\"ace\\"\\n输出：3"]', '["Amazon","Google"]', 1719000000000, 1719000000000),
('p-edit-distance', '编辑距离', 'MEDIUM', '["字符串","动态规划"]', '给你两个单词 word1 和 word2，请返回将 word1 转换成 word2 所使用的最少操作数。你可以对一个单词进行插入、删除、替换操作。', '["0 <= word1.length, word2.length <= 500"]', '["输入：word1 = \\"horse\\", word2 = \\"ros\\"\\n输出：3"]', '["Amazon","Google","Microsoft"]', 1719000000000, 1719000000000),
('p-permutations', '全排列', 'MEDIUM', '["数组","回溯"]', '给定一个不含重复数字的数组 nums，返回其所有可能的全排列。你可以按任意顺序返回答案。', '["1 <= nums.length <= 6","-10 <= nums[i] <= 10","nums 中的所有整数互不相同"]', '["输入：nums = [1,2,3]\\n输出：[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]"]', '["Amazon","Meta","Microsoft"]', 1719000000000, 1719000000000),
('p-subsets', '子集', 'MEDIUM', '["位运算","数组","回溯"]', '给你一个整数数组 nums，数组中的元素互不相同。返回该数组所有可能的子集（幂集）。', '["1 <= nums.length <= 10","-10 <= nums[i] <= 10","nums 中的所有元素互不相同"]', '["输入：nums = [1,2,3]\\n输出：[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]"]', '["Amazon","Meta","Google"]', 1719000000000, 1719000000000),
('p-word-ladder', '单词接龙', 'HARD', '["BFS","哈希表","字符串"]', '给定字典中两个单词 beginWord 和 endWord，找到从 beginWord 到 endWord 的最短转换序列长度。', '["1 <= beginWord.length <= 10","endWord.length == beginWord.length","1 <= wordList.length <= 5000"]', '["输入：beginWord = \\"hit\\", endWord = \\"cog\\", wordList = [\\"hot\\",\\"dot\\",\\"dog\\",\\"lot\\",\\"log\\",\\"cog\\"]\\n输出：5"]', '["Amazon","Google","Meta"]', 1719000000000, 1719000000000),
('p-rotting-oranges', '腐烂的橘子', 'MEDIUM', '["BFS","数组","矩阵"]', '在给定的 m x n 网格中，每个单元格可以有以下三个值之一：0 空、1 新鲜橘子、2 腐烂橘子。每分钟腐烂的橘子会使上下左右相邻的新鲜橘子腐烂，求所有橘子腐烂的最少分钟数。', '["m == grid.length","n == grid[i].length","1 <= m, n <= 10"]', '["输入：grid = [[2,1,1],[1,1,0],[0,1,1]]\\n输出：4"]', '["Amazon","Google","Microsoft"]', 1719000000000, 1719000000000);

-- 3. 插入示例解析（为"两数之和"插入 L3 级别解析）
INSERT INTO explanations (id, problem_id, level, status, is_latest, version, sections, created_at, updated_at) VALUES
('exp-two-sum-l3', 'p-two-sum', 3, 'PUBLISHED', 1, 1, '[{"title":"核心思路","contentType":"text","content":"## 哈希表一次遍历\\n\\n遍历数组时，对每个元素 `nums[i]`，计算 `complement = target - nums[i]`。\\n\\n如果 `complement` 已经在哈希表中，说明找到了答案。否则，将 `nums[i]` 存入哈希表。\\n\\n**时间复杂度 O(n)**，空间复杂度 O(n)。"},{"title":"代码实现","contentType":"code","content":"","approaches":[{"name":"哈希表法","idea":"一次遍历 + 哈希查找 complement","code":{"python":"def twoSum(nums, target):\\n    seen = {}\\n    for i, num in enumerate(nums):\\n        complement = target - num\\n        if complement in seen:\\n            return [seen[complement], i]\\n        seen[num] = i\\n    return []","java":"public int[] twoSum(int[] nums, int target) {\\n    Map<Integer, Integer> map = new HashMap<>();\\n    for (int i = 0; i < nums.length; i++) {\\n        int complement = target - nums[i];\\n        if (map.containsKey(complement)) {\\n            return new int[]{map.get(complement), i};\\n        }\\n        map.put(nums[i], i);\\n    }\\n    return new int[]{};\\n}"},"timeComplexity":"O(n)","spaceComplexity":"O(n)","whyThisWorks":"哈希表提供 O(1) 查找","whenToUse":"需要在数组中找配对元素","limitations":"需要额外空间"},{"name":"暴力枚举","idea":"双重循环逐一比较","code":{"python":"def twoSum(nums, target):\\n    for i in range(len(nums)):\\n        for j in range(i+1, len(nums)):\\n            if nums[i] + nums[j] == target:\\n                return [i, j]\\n    return []","java":"public int[] twoSum(int[] nums, int target) {\\n    for (int i = 0; i < nums.length; i++) {\\n        for (int j = i + 1; j < nums.length; j++) {\\n            if (nums[i] + nums[j] == target)\\n                return new int[]{i, j};\\n        }\\n    }\\n    return new int[]{};\\n}"},"timeComplexity":"O(n²)","spaceComplexity":"O(1)","whyThisWorks":"穷举所有组合","whenToUse":"数组极小时可用","limitations":"超时风险"}]}]', 1719000000000, 1719000000000),
('exp-climbing-l3', 'p-climbing-stairs', 3, 'PUBLISHED', 1, 1, '[{"title":"核心思路","contentType":"text","content":"## 斐波那契数列\\n\\n到达第 n 阶的方法 = 到达第 n-1 阶的方法 + 到达第 n-2 阶的方法。\\n\\n状态转移方程：`dp[i] = dp[i-1] + dp[i-2]`\\n\\n这就是斐波那契数列！可以用 O(1) 空间优化。"},{"title":"代码实现","contentType":"code","content":"","approaches":[{"name":"动态规划","idea":"自底向上递推","code":{"python":"def climbStairs(n):\\n    if n <= 2: return n\\n    prev, curr = 1, 2\\n    for _ in range(3, n+1):\\n        prev, curr = curr, prev + curr\\n    return curr","java":"public int climbStairs(int n) {\\n    if (n <= 2) return n;\\n    int prev = 1, curr = 2;\\n    for (int i = 3; i <= n; i++) {\\n        int temp = curr;\\n        curr = prev + curr;\\n        prev = temp;\\n    }\\n    return curr;\\n}"},"timeComplexity":"O(n)","spaceComplexity":"O(1)","whyThisWorks":"利用最优子结构递推","whenToUse":"线性递推问题","limitations":"无"}]}]', 1719000000000, 1719000000000);

-- 4. 创建管理员账户（密码: Admin123456，BCrypt 加密）
-- BCrypt hash for "Admin123456"
INSERT INTO users (id, email, nickname, password_hash, role, tier, created_at) VALUES
(UNHEX(REPLACE(UUID(), '-', '')), 'admin@algorithm-help.com', '管理员', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMIN', 'PRO', 1719000000000);

-- 5. 插入题目关联关系
INSERT INTO problem_relations (id, source_problem_id, target_problem_id, relation_type, confidence, description, created_at) VALUES
(UUID(), 'p-two-sum', 'p-three-sum', 'follow_up', 0.95, '三数之和是两数之和的进阶版', 1719000000000),
(UUID(), 'p-climbing-stairs', 'p-house-robber', 'similar_pattern', 0.9, '都是线性DP，状态转移相似', 1719000000000),
(UUID(), 'p-longest-substring-without-repeating', 'p-container-with-most-water', 'similar_pattern', 0.7, '都使用双指针/滑动窗口思想', 1719000000000),
(UUID(), 'p-longest-common-subsequence', 'p-edit-distance', 'similar_pattern', 0.92, '都是二维DP，状态定义相似', 1719000000000),
(UUID(), 'p-binary-tree-level-order', 'p-rotting-oranges', 'similar_pattern', 0.85, '都是 BFS 层序遍历的应用', 1719000000000);
